import type { AdminTab } from './types';

export interface PrimaryAdminModule {
  id: AdminTab;
  label: string;
  defaultSubAction: string;
}

export const PRIMARY_ADMIN_MODULES: PrimaryAdminModule[] = [
  { id: 'administracion', label: 'Administración', defaultSubAction: 'datos_emisor' },
  { id: 'inventario', label: 'Catálogo e Inventario', defaultSubAction: 'productos' },
  { id: 'ventas', label: 'Comercial', defaultSubAction: 'listado_ventas' },
  { id: 'compras', label: 'Abastecimiento', defaultSubAction: 'listado_compras' },
  { id: 'tesoreria', label: 'Tesorería', defaultSubAction: 'gestion_cajas' },
  { id: 'contabilidad', label: 'Contabilidad y Fiscal', defaultSubAction: 'plan_cuentas' },
  { id: 'analitica', label: 'Analítica y Control', defaultSubAction: 'ventas_totales' },
  { id: 'operaciones', label: 'Operaciones', defaultSubAction: 'ordenes_prod' },
  { id: 'rrhh', label: 'Recursos Humanos', defaultSubAction: 'empleados' },
];

const DEFAULT_SUB_ACTION_BY_TAB: Partial<Record<AdminTab, string>> = {
  administracion: 'datos_emisor',
  inventario: 'productos',
  compras: 'listado_compras',
  tesoreria: 'gestion_cajas',
  cartera: 'cuentas_cobrar',
  pagos: 'cuentas_pagar',
  operaciones: 'ordenes_prod',
  produccion: 'ordenes_prod',
  rrhh: 'empleados',
  nomina: 'empleados',
  activos: 'listado_activos',
  contabilidad: 'plan_cuentas',
  analitica: 'ventas_totales',
  tablero: 'ventas_totales',
  movil: 'pos_movil',
  soporte: 'soporte_tecnico',
  matriz_permisos: 'matriz_permisos',
  aprobaciones: 'aprobaciones',
  kardex_stock: 'kardex',
};

export const getDefaultAdminSubAction = (tab: AdminTab): string =>
  DEFAULT_SUB_ACTION_BY_TAB[tab] ?? 'listado_ventas';

export const SUB_ACTION_LABELS: Record<string, string> = {
  clientes: 'Clientes',
  entregas: 'Entregas por Facturar',
  proformas: 'Proformas',
  pedidos: 'Pedidos',
  whatsapp: 'Marketing WhatsApp',
  agentes: 'Agentes de Ventas',
  secuencias: 'Secuencias Documentos',
  tarjetas: 'Tarjetas Clientes',
  comisiones: 'Liquidacion Comisiones',
  impresion_lotes: 'Impresion Facturas Lotes',
  docs_electronicos: 'Documentos Electronicos SRI',
  listado_ventas: 'Listado Ventas',
  tablero_ventas: 'Tablero de Control Ventas',
  avisos: 'Avisos Importantes',
  productos: 'Productos & Servicios',
  categorias: 'Categorias de Producto',
  lineas: 'Lineas de Producto',
  tarifas: 'Tarifas / Precios',
  entradas: 'Entradas Inventario',
  salidas: 'Salidas y Ajustes',
  kardex: 'Kardex de Productos',
  stock_minimo: 'Stock Minimo',
  ajuste_fisico: 'Ajuste Fisico',
  proveedores: 'Proveedores',
  ordenes_compra: 'Ordenes de Compra',
  nueva_compra: 'Nueva Compra',
  facturas_compra: 'Facturas Proveedor',
  liquidaciones: 'Liquidaciones de Compra',
  retenciones: 'Comprobantes de Retencion',
  listado_compras: 'Listado Compras',
  gestion_cajas: 'Gestion de Cajas',
  transacciones_caja: 'Transacciones de Caja',
  cierre_caja: 'Arqueo & Cierre',
  bancos: 'Bancos & Cuentas',
  depositos: 'Depositos Bancarios',
  vouchers: 'Liquidacion Vouchers',
  resumen_tesoreria: 'Resumen Cajas',
  cuentas_cobrar: 'Cuentas por Cobrar',
  registrar_cobro: 'Registrar Cobro',
  anticipos_clientes: 'Anticipos Clientes',
  estado_cuenta: 'Estado de Cuenta',
  vencimientos: 'Vencimiento Cartera',
  cuentas_pagar: 'Cuentas por Pagar',
  pago_proveedores: 'Pago a Proveedores',
  egresos_caja: 'Egresos de Caja',
  ordenes_prod: 'Ordenes Produccion',
  recetas: 'Recetas & Formulas',
  materia_prima: 'Materia Prima',
  empleados: 'Empleados',
  roles_pago: 'Roles de Pago',
  asistencia: 'Asistencia & Horarios',
  plan_cuentas: 'Plan de Cuentas',
  asientos: 'Asientos Contables',
  libro_diario: 'Libro Diario',
  balance_general: 'Balance General',
  pyg: 'Perdidas y Ganancias',
  ats_sri: 'Anexo ATS SRI',
  ventas_facturador: 'Ventas por Facturador',
  ventas_vendedor: 'Ventas por Vendedor',
  ventas_totales: 'Ventas Totales',
  top_clientes: 'Top 10 Clientes',
  datos_emisor: 'Datos Emisor SRI',
  establecimientos: 'Establecimientos SRI',
  firma_p12: 'Firma Electronica',
  api_sri: 'API Facturacion',
  usuarios_roles: 'Usuarios y Roles',
  matriz_permisos: 'Matriz de Permisos RBAC',
  aprobaciones: 'Solicitudes y Aprobaciones',
  auditoria: 'Auditoria de Sistema',
  listado_activos: 'Bienes y Equipos',
  depreciacion: 'Depreciacion Activos',
  pos_movil: 'Terminales POS Moviles',
  sincronizacion_movil: 'Sincronizacion Movil',
  soporte_tecnico: 'Soporte Tecnico',
  licencia_sistema: 'Licencia del Sistema',
};
